LampShade/ServiceHost/Areas/Administration/Pages/Accounts/Account/Index.cshtml.cs
using System.Collections.Generic;
using AccountManagement.Application.Contracts.Account;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Account
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { set; get; }
        public AccountSearchModel SearchModel;
        public List<AccountViewModel> Accounts;
        public SelectList Roles;

        private readonly IAccountApplication _accountApplication;
        private readonly IRoleApplication _roleApplication;
        public IndexModel(IAccountApplication accountApplication, IRoleApplication roleApplication)
        {
            _accountApplication = accountApplication;
            _roleApplication = roleApplication;
        }


        public void OnGet(AccountSearchModel searchModel)
        { 
            Roles = new SelectList(_roleApplication.GetList(), "Id", "Name");
            Accounts = _accountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()

        {
            var command = new CreateAccount
            {
                Roles = _roleApplication.GetList()
            };
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateAccount command)
        {
            var result = _accountApplication.Create(command);

            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var account = _accountApplication.GetDetails(id);
            account.Roles = _roleApplication.GetList();
            return Partial("Edit", account);
        }
       
        public JsonResult OnPostEdit(EditAccount command)
        {
            var result = _accountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetChangePassword(long id)
        {
            var command = new ChangePassword{Id = id};
            return Partial("ChangePassword", command);
        }

        public JsonResult OnPostChangePassword(ChangePassword command)
        {
            var result = _accountApplication.ChangePassword(command);
            return new JsonResult(result);
        }

    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Accounts/Role/Index.cshtml.cs
using System.Collections.Generic;
using AccountManagement.Application.Contracts.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { set; get; }
        public List<RoleViewModel> Roles;

        private readonly IRoleApplication _roleApplication;
        public IndexModel( IRoleApplication roleApplication)
        {
           
            _roleApplication = roleApplication;
        }


        public void OnGet( )
        {
            Roles = _roleApplication.GetList();
        }

        public IActionResult OnGetCreate()

        {
            var command = new CreateRole()
            {
                
            };
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateRole command)
        {
            var result = _roleApplication.Create(command);

            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var Role = _roleApplication.GetDetails(id);
            
            return Partial("Edit", Role);
        }
       
        public JsonResult OnPostEdit(EditRole command)
        {
            var result = _roleApplication.Edit(command);
            return new JsonResult(result);
        }


    }
}
 

LampShade/ServiceHost/Areas/Administration/Pages/Blog/ArticleCategories/Index.cshtml.cs
using System.Collections.Generic;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Blog.ArticleCategories
{
    public class IndexModel : PageModel
    {
        public string Message;
        public ArticleCategoryViewModel SearchModel;
        public List<ArticleCategoryViewModel> ArticleCategories;
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public IndexModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(ArticleCategorySearchModel searchModel)
        {
            ArticleCategories = _articleCategoryApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateArticleCategory());
        }

        public JsonResult OnPostCreate(CreateArticleCategory command)
        {
            var result = _articleCategoryApplication.Create(command);

            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var articleCategory = _articleCategoryApplication.GetDetails(id);
            return Partial("Edit", articleCategory);
        }

        public JsonResult OnPostEdit(EditArticleCategory command)
        {
            if (ModelState.IsValid)
            {
                var result = _articleCategoryApplication.Edit(command);
                return new JsonResult(result);
            }

            return new JsonResult("فرمت فایل مجاز نمی باشد.");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Blog/Articles/Create.cshtml.cs
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class CreateModel : PageModel
    {
        public SelectList ArticleCategories;
        public CreateArticle Command;

        private readonly IArticleCategoryApplication _articleCategoryApplication;
        private readonly IArticleApplication _articleApplication;
        public CreateModel(IArticleCategoryApplication articleCategoryApplication, IArticleApplication articleApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost(CreateArticle command)
        {
            var result = _articleApplication.Create(command);

            return RedirectToPage("./index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Blog/Articles/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class EditModel : PageModel
    {
        public EditArticle Command;
        public SelectList ArticleCategories;


        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;
        public EditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(long id)
        {
            Command = _articleApplication.GetDetails(id);
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost(EditArticle command)
        {
            _articleApplication.Edit(command);
            return RedirectToPage("./index");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Blog/Articles/Index.cshtml.cs
using System.Collections.Generic;
using BlogManagement.Application.Contracts.Article;
using BlogManagement.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Articles
{
    public class IndexModel : PageModel
    {
        public string Message;
        public ArticleSearchModel SearchModel;
        public List<ArticleViewModel> Articles;
        public SelectList ArticleCategories;

        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;
        public IndexModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(ArticleSearchModel searchModel)
        {
            Articles = _articleApplication.Search(searchModel);
            ArticleCategories = new SelectList(_articleCategoryApplication.GetArticleCategories(), "Id", "Name");
        }

    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Shop/ProductCategories/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductCategories
{
    public class IndexModel : PageModel
    {
        public string Message;
        public ProductCategorySearchModel SearchModel;
        public List<ProductCategoryViewModel> ProductCategories;
        private readonly IProductCategoryApplication _productCategoryApplication;

        public IndexModel(IProductCategoryApplication productCategoryApplication)
        {
            _productCategoryApplication = productCategoryApplication;
        }

        public void OnGet(ProductCategorySearchModel searchModel)
        {
            ProductCategories = _productCategoryApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateProductCategory());
        }

        public JsonResult OnPostCreate(CreateProductCategory command)
        {
            var result = _productCategoryApplication.Create(command);

            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var productCategory = _productCategoryApplication.GetDetails(id);
            return Partial("Edit", productCategory);
        }

        public JsonResult OnPostEdit(EditProductCategory command)
        {
            if (ModelState.IsValid)
            {
                var result = _productCategoryApplication.Edit(command);
                return new JsonResult(result);
            }

            return new JsonResult("فرمت فایل مجاز نمی باشد.");
        }
    }
}

LampShade/ServiceHost/Areas/Administration/Pages/Shop/Products/Index.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;

namespace ServiceHost.Areas.Administration.Pages.Shop.Products
{
    public class IndexModel : PageModel
    {
        [TempData]
        public string Message { set; get; }
        public ProductSearchModel SearchModel;
        public List<ProductViewModel> Products;
        public SelectList ProductCategories;

        private readonly IProductCategoryApplication _productCategoryApplication;
        private readonly IProductApplication _productApplication;

        public IndexModel(IProductApplication productApplication, IProductCategoryApplication productCategoryApplication)
        {
            _productApplication = productApplication;
            _productCategoryApplication = productCategoryApplication;
        }


        public void OnGet(ProductSearchModel searchModel)
        {
            ProductCategories = new SelectList(_productCategoryApplication.GetProductCategories(), "Id", "Name");
            Products = _productApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()

        {
            var command = new CreateProduct
            {
                Categories = _productCategoryApplication.GetProductCategories()
            };
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(CreateProduct command)
        {
            var result = _productApplication.Create(command);

            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var product = _productApplication.GetDetails(id);
            product.Categories = _productCategoryApplication.GetProductCategories();
            return Partial("Edit", product);
        }

        public JsonResult OnPostEdit(EditProduct command)
        {
            var result = _productApplication.Edit(command);
            return new JsonResult(result);
        }

       
    }
}

LampShade/ServiceHost/Pages/Account.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountManagement.Application.Contracts.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Pages
{
    public class AccountModel : PageModel
    {
        [TempData]
        public string Message { get; set; }
        private readonly IAccountApplication _accountApplication;

        public AccountModel(IAccountApplication accountApplication)
        {
            _accountApplication = accountApplication;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPostLogin(Login command)
        {
             var result = _accountApplication.Login(command);
            if (result.IsSuccess)
            {
                Message = result.Message;
                return RedirectToPage("/index",new { Message });
            }
                

            Message = result.Message;
            return RedirectToPage("/account");
        }

        public IActionResult OnGetLogout()
        {
           var result= _accountApplication.Logout();

           Message = result.Message;
           return RedirectToPage("/Index",new{Message});

        }
    }
}

LampShade/ServiceHost/ViewComponents/LatestArrivalsViewComponent.cs
using _01_LampShadeQuery.Contract.Product;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class LatestArrivalsViewComponent:ViewComponent
    {
        private readonly IProductQuery _productQuery;

        public LatestArrivalsViewComponent(IProductQuery productQuery)
        {
            _productQuery = productQuery;
        }

        public IViewComponentResult Invoke()
        {
            var products = _productQuery.GetLatestArrivals();
            return View(products);
        }
    }
}

LampShade/ServiceHost/ViewComponents/LatestArticlesViewComponent.cs
using _01_LampShadeQuery.Contract.Article;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class LatestArticlesViewComponent:ViewComponent
    {
        private readonly IArticleQuery _articleQuery;

        public LatestArticlesViewComponent(IArticleQuery articleQuery)
        {
            _articleQuery = articleQuery;
        }

        public IViewComponentResult Invoke()
        {
            var articles = _articleQuery.LatestArticles();
            return View(articles);
        }
    }
}

LampShade/ServiceHost/ViewComponents/ProductCategoryViewComponent.cs
using _01_LampShadeQuery.Contract.ProductCategory;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class ProductCategoryViewComponent :ViewComponent
    {
        private readonly IProductCategoryQuery _productCategoryQuery;

        public ProductCategoryViewComponent(IProductCategoryQuery productCategoryQuery)
        {
            _productCategoryQuery = productCategoryQuery;
        }

        public IViewComponentResult Invoke()
        {
            var productCategories = _productCategoryQuery.GetList();
            return View(productCategories);
        }
    }
}

LampShade/ServiceHost/ViewComponents/SlideViewComponent.cs
using _01_LampShadeQuery.Contract.Slide;
using Microsoft.AspNetCore.Mvc;

namespace ServiceHost.ViewComponents
{
    public class SlideViewComponent :ViewComponent
    {
        private readonly ISlideQuery _slideQuery;

        public SlideViewComponent(ISlideQuery slideQuery)
        {
            _slideQuery = slideQuery;
        }

        public IViewComponentResult Invoke()
        {
            var slides = _slideQuery.GetList();
            return View(slides);
        }
    }
}

LampShade/ServiceHost/Pages/Account.cshtml
@page
@model ServiceHost.Pages.AccountModel
@{
    ViewData["Title"] = "ورود و ثبت نام";
}



<div class="breadcrumb-area section-space--half">
    <div class="container wide">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb-wrapper breadcrumb-bg">
                    <div class="breadcrumb-content">
                        <h2 class="breadcrumb-content__title">ورود و ثبت نام</h2>
                        <ul class="breadcrumb-content__page-map">
                            <li><a asp-page="/Index">صفحه اصلی</a></li>
                            <li class="active">ورود - ثبت نام</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="page-content-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="page-wrapper">
                    <div class="page-content-wrapper">
                        <div class="row">
                            <div class="col-sm-12 col-md-12 col-xs-12 col-lg-6">
                                @if (Model.Message!=null)
                                {
                                    <div class="alert alert-danger">@Model.Message</div>
                                }

                                <form method="post" asp-page-handler="Login">
                                    <div class="login-form">
                                        <h4 class="login-title">ورود</h4>
                                        <div class="row">
                                            <div class="col-md-12 col-12">
                                                <label> نام کاربری*</label>
                                                <input type="text" name="UserName" placeholder="نام کاربری">
                                            </div>
                                            <div class="col-12">
                                                <label>رمز ورود</label>
                                                <input type="password" name="Password" placeholder="رمز ورود">
                                            </div>

                                            <div class="col-sm-6 text-left text-sm-right">
                                                <a href="#" class="forget-pass-link"> رمز را فراموش کرده اید؟</a>
                                            </div>

                                            <div class="col-md-12">
                                                <button class="register-button">ورود</button>
                                            </div>

                                        </div>
                                    </div>

                                </form>
                            </div>
                            <div class="col-sm-12 col-md-12 col-lg-6 col-xs-12">
                                <form action="#">

                                    <div class="login-form">
                                        <h4 class="login-title">ثبت نام</h4>

                                        <div class="row">
                                            <div class="col-md-6 col-12 mb-20">
                                                <label> نام </label>
                                                <input type="text" name="FullName" placeholder=" نام">
                                            </div>
                                            <div class="col-md-6 col-12 mb-20">
                                                <label> نام کاربری</label>
                                                <input type="text" name="UserName" placeholder="نام کاربری">
                                            </div>
                                            <div class="col-md-12 mb-20">
                                                <label>موبایل </label>
                                                <input type="text" name="Mobile" placeholder="موبایل">
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label>کلمه عبور</label>
                                                <input type="password" name="Password" placeholder="کلمه عبور">
                                            </div>
                                            <div class="col-md-6 mb-20">
                                                <label>تایید کلمه عبور </label>
                                                <input type="password" name="Repassword" placeholder="تایید کلمه عبور ">
                                            </div>
                                            <div class="col-12">
                                                <button class="register-button mt-0">ثبت نام</button>
                                            </div>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LampShade/ServiceHost/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = " صفحه اصلی";
}

@if (Model.Message != null)
{
    <div id="alertMessage" class="alert alert-success alertMessage">@Model.Message</div>
}

@await Component.InvokeAsync("Slide")

@await Component.InvokeAsync("ProductCategory")

@await Component.InvokeAsync("ProductCategoryWithProduct")

@await Component.InvokeAsync("LatestArrivals")

<div class="banner-hover-area section-space">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="banner-hover-wrapper">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="single-hover-banner">
                                <div class="single-hover-banner__image">
                                    <a href="shop-left-sidebar.html">
                                        <img src="~/Theme/assets/img/banners/img1-middle-eposi1.jpg" class="img-fluid"
                                             alt="">
                                    </a>
                                    <div class="single-hover-banner__content">
                                        <h4 class="small-text">Black Friday</h4>
                                        <h3 class="big-text">Save Up To 50% Off</h3>
                                        <a class="banner-link" href="shop-left-sidebar.html">SHOP NOW</a>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="single-hover-banner">
                                <div class="single-hover-banner__image">
                                    <a href="shop-left-sidebar.html">
                                        <img src="~/Theme/assets/img/banners/img2-middle-eposi1.jpg" class="img-fluid"
                                             alt="">
                                    </a>
                                    <div class="single-hover-banner__content">
                                        <h4 class="small-text">Best Selling !</h4>
                                        <h3 class="big-text">Living Room Up To 70% Off</h3>
                                        <a class="banner-link" href="shop-left-sidebar.html">SHOP NOW</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="feature-logo-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="feature-logo-wrapper section-space--inner-bottom">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/free_shipping.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">FREE SHIPPING WORLDWIDE</h4>
                                    <p class="short-desc">
                                        We offer free shipping via Standard Shipping on orders
                                        over $200.00
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/money_back.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">MONEY BACK GUARANTEE</h4>
                                    <p class="short-desc">
                                        If you're not satisfied with our product, we'll refund the
                                        purchase price*.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="single-feature-logo">
                                <div class="single-feature-logo__image">
                                    <img src="~/Theme/assets/img/icons/support247.png" class="img-fluid" alt="">
                                </div>
                                <div class="single-feature-logo__content">
                                    <h4 class="title">ONLINE SUPPORT 24/7</h4>
                                    <p class="short-desc">
                                        Our friendly support team is available to help you 24
                                        hours a day, seven days a week
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@await Component.InvokeAsync("LatestArticles")

<div class="newsletter-area section-space--inner">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 offset-lg-2">
                <div class="newsletter-wrapper">
                    <p class="small-text">Special Ofers For Subscribers</p>
                    <h3 class="title">Ten Percent Member Discount</h3>
                    <p class="short-desc">
                        Subscribe to our newsletters now and stay up to date with new collections,
                        the latest lookbooks and exclusive offers.
                    </p>

                    <div class="newsletter-form">
                        <form id="mc-form" class="mc-form">
                            <input type="email" placeholder="Enter Your Email Address Here..." required>
                            <button type="submit" value="submit">SUBSCRIBE</button>
                        </form>

                    </div>
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>